name: Publish ARC

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      release_tag_name:
        description: 'The tag name of the release to publish'
        required: true
      push_to_registries:
        description: 'Whether to push the image to registries'
        required: true
        type: boolean
        default: false

permissions:
 contents: write 
 packages: write

env:
  TARGET_ORG: actions-runner-controller
  TARGET_REPO: actions-runner-controller

jobs:
  release-controller:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make github-release

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.ACTIONS_ACCESS_APP_ID }}
          application_private_key: ${{ secrets.ACTIONS_ACCESS_PK }}
          organization: ${{ env.TARGET_ORG }}

      - name: Trigger Build And Push Images To Registries
        # Revert to https://github.com/actions-runner-controller/releases#releases
        # for details on why we use this approach
        run: |
          # Define the release tag name based on the event type
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "RELEASE_TAG_NAME=$(cat ${GITHUB_EVENT_PATH} | jq -r '.release.tag_name')" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
              echo "RELEASE_TAG_NAME=${{ github.event.inputs.release_tag_name }}" >> $GITHUB_ENV
          fi

          # Authenticate
          gh auth login --with-token ${{ steps.get_workflow_token.outputs.token }}

          # Trigger the workflow
          jq -n '{"event_type": "arc", "client_payload": {"release_tag_name": "${RELEASE_TAG_NAME}", "push_to_registries": ${{ inputs.push_to_registries }}}}' \
            | gh api -X POST /repos/actions-runner-controller/releases/dispatches --input -
